import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { appendEvent, writeRevision, loadState } from "../src/store.js";
import { setAnalysis, setUnitViewed, setUnit } from "../src/service.js";
import { toRevisionFiles } from "../src/migration.js";
import { describe, expect, it } from "vitest";
import { detectGenerated, normalizeGeneratedUnits, GENERATED_UNIT_ID } from "../src/generated.js";
import { parseDiff } from "../src/parse-diff.js";
import { applyEvent, initialState } from "../src/reducer.js";
import { StateSchema, type ReviewerEvent, type ReviewUnit } from "../src/schemas.js";

const file = (body: string) => parseDiff(`diff --git a/client.ts b/client.ts
--- a/client.ts
+++ b/client.ts
@@ -1,2 +1,2 @@
${body}
`)[0];
const revision = (n: number, path = "client.ts", oldPath?: string): ReviewerEvent => ({
  ts: "2026-01-01", type: "revision-added", revision: n,
  baseSha: "base", headSha: `head${n}`, mergeBase: "base",
  files: [{ path, oldPath, hunkIds: [`h${n}`], generatedReason: "Generated-file header" }],
});
const unit: ReviewUnit = { id: "authored", title: "Authored", summary: "", kind: "wiring", attention: "must-read", attentionWhy: "", riskFlags: [], hunkIds: ["h1", "source"], order: 1 };

describe("generated files", () => {
  it("recognizes comment headers, but not removed markers or strings", () => {
    expect(detectGenerated(file(" // Code generated by protoc. DO NOT EDIT.\n-old\n+new"), [])).toBe("Generated-file header");
    expect(detectGenerated(file("-// @generated\n+// Hand maintained"), [])).toBeUndefined();
    expect(detectGenerated(file('+const x = "// @generated";'), [])).toBeUndefined();
    expect(detectGenerated(file("+// @generated"), [])).toBe("Generated-file header");
  });
  it("uses explicit repository patterns, keeping lockfiles opt-in", () => {
    const f = file("+hello");
    expect(detectGenerated({ ...f, path: "pnpm-lock.yaml" }, [])).toBeUndefined();
    expect(detectGenerated({ ...f, path: "api/types.gen.ts" }, ["**/*.gen.ts"])).toContain("Repository rule");
    expect(detectGenerated({ ...f, path: "types.gen.ts" }, ["**/*.gen.ts"])).toContain("Repository rule");
    expect(detectGenerated({ ...f, path: "src/main.ts" }, ["api/*"])).toBeUndefined();
  });
  it("auto-views and creates one stable unit before analysis, preserving it on reanalysis", () => {
    let state = applyEvent(initialState(), revision(1));
    expect(state.files[0].viewed).toBe(true);
    expect(state.hunks.h1.autoViewed).toBe(true);
    expect(state.units[0].id).toBe(GENERATED_UNIT_ID);
    state = applyEvent(state, { ts: "", type: "analysis-set", revision: 1, summary: "Review", units: [unit], unassigned: ["h1"] });
    expect(state.units.find((u) => u.id === "authored")?.hunkIds).toEqual(["source"]);
    expect(state.units.filter((u) => u.generated)).toHaveLength(1);
    expect(state.unassignedHunkIds).toEqual([]);
    expect(normalizeGeneratedUnits(state.files, state.units)).toEqual(state.units);
  });
  it("persists a file override across new hunks, schema round trips and renames", () => {
    let state = applyEvent(initialState(), revision(1));
    state = applyEvent(state, { ts: "", type: "hunk-unviewed", hunkId: "h1", revision: 1 });
    state = StateSchema.parse(JSON.parse(JSON.stringify(state)));
    state = applyEvent(state, revision(2));
    expect(state.hunks.h2.viewed).toBe(false);
    state = applyEvent(state, revision(3, "renamed.ts", "client.ts"));
    expect(state.hunks.h3.viewed).toBe(false);
    expect(state.generatedManualPaths).toContain("renamed.ts");
  });
  it("auto-views new generated hunks and removes the unit when no generated files remain", () => {
    let state = applyEvent(initialState(), revision(1));
    state = applyEvent(state, revision(2));
    expect(state.hunks.h2.autoViewed).toBe(true);
    state = applyEvent(state, { ...revision(3), files: [] } as ReviewerEvent);
    expect(state.units).toEqual([]);
  });
});


it("upgrades existing stored revisions on analysis and preserves unit unview overrides", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "purview-generated-"));
  const key = { host: "github.com", owner: "acme", repo: "widgets", number: 1 };
  try {
    const f = file(" // @generated\n-old\n+new");
    writeRevision(key, 1, "", [f], { baseSha: "b", headSha: "h", mergeBase: "b" }, root);
    appendEvent(key, { type: "revision-added", revision: 1, baseSha: "b", headSha: "h", mergeBase: "b", files: toRevisionFiles([f]) }, root);
    const first = setAnalysis(key, { summary: "Generated only", units: [] }, root);
    expect(first.coverage.missing).toEqual([]);
    expect(first.state.files[0].viewed).toBe(true);
    expect(() => setUnit(key, GENERATED_UNIT_ID, { attention: "skim" }, {}, root)).toThrow("managed unit");
    setUnitViewed(key, GENERATED_UNIT_ID, false, root);
    setAnalysis(key, { summary: "Again", units: [] }, root);
    expect(loadState(key, root).hunks[f.hunks[0].id].viewed).toBe(false);
    expect(() => setAnalysis(key, { summary: "", units: [{ ...unit, id: GENERATED_UNIT_ID, hunkIds: ["unknown"] }] }, root)).toThrow("not in");
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

it("unviews automatically viewed hunks when a classification is removed", () => {
  let state = applyEvent(initialState(), revision(1));
  state = applyEvent(state, { ts: "", type: "generated-files-classified", revision: 1, files: [{ path: "client.ts" }] });
  expect(state.hunks.h1.viewed).toBe(false);
  expect(state.hunks.h1.autoViewed).toBe(false);
  expect(state.units).toEqual([]);
});
