import { afterEach, beforeEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { setGhRunner } from "../src/github.js";
import {
  GENERATED_UNIT_ID,
  classifyGenerated,
  gitattributesVerdict,
  markerIn,
  matchesPattern,
  parseGitattributes,
  repoVerdict,
  withGeneratedOverride,
} from "../src/generated.js";
import { setGeneratedOverride } from "../src/generated-io.js";
import { parseDiff } from "../src/parse-diff.js";
import { readiness, analysisUnits, fold } from "../src/reducer.js";
import { renderTriage } from "../src/triage.js";
import { selectHunks, allSelectedHunks } from "../src/hunk-select.js";
import {
  discardRevision,
  initPr,
  refreshPr,
  setAnalysis,
  setUnitViewed,
  setUnits,
} from "../src/service.js";
import { readEvents, readFilesJson, readGeneratedFacts, readRepoConfig, writeRepoConfig } from "../src/store.js";
import { needsClassification } from "../src/unit-patch.js";
import type { PrKey } from "../src/paths.js";
import type { FileDiff, State } from "../src/schemas.js";

/* ------------------------------------------------------------- fixtures */

const file = (p: string, body: string, opts: { added?: boolean; start?: number } = {}) => {
  const start = opts.start ?? 10;
  const lines = body.split("\n");
  return opts.added
    ? `diff --git a/${p} b/${p}\nnew file mode 100644\nindex 0000000..1111111\n--- /dev/null\n+++ b/${p}\n` +
        `@@ -0,0 +1,${lines.length} @@\n` +
        lines.map((l) => `+${l}`).join("\n") +
        "\n"
    : `diff --git a/${p} b/${p}\nindex 1111111..2222222 100644\n--- a/${p}\n+++ b/${p}\n` +
        `@@ -${start},2 +${start},${1 + lines.length} @@ ctx\n ctx\n` +
        lines.map((l) => `+${l}`).join("\n") +
        "\n ctx\n";
};

const SRC = file("src/app.ts", "const a = 1;");
const LOCK = file("pnpm-lock.yaml", "  foo: 1.0.0\n  bar: 2.0.0");
const PB = file("api/v1/thing.pb.go", "func (x *Thing) Reset() {}");
const MARKED = file("gen/client.ts", "// Code generated by openapi-gen. DO NOT EDIT.\nexport {};", { added: true });
const MOCK = file("internal/mocks/mocks.go", "func (m *Mock) Do() {}", { start: 40 });
const ATTR = file("schema/out.graphql", "type Q { a: Int }");

const REV1 = SRC + LOCK + PB + MARKED + MOCK + ATTR;
const REV2 = file("src/app.ts", "const a = 2;") + LOCK + file("api/v1/thing.pb.go", "func (x *Thing) Reset2() {}") + MOCK + ATTR;

/* ------------------------------------------------------------- pure */

describe("classification (pure)", () => {
  const files = parseDiff(REV1);

  it("orders the signals: repo > gitattributes > lockfile > path > marker", () => {
    const v = classifyGenerated(
      files,
      {
        gitattributes: "schema/*.graphql linguist-generated\n*.pb.go -linguist-generated\n",
        markers: { "gen/client.ts": "Code generated by openapi-gen. DO NOT EDIT.", "internal/mocks/mocks.go": "Code generated by mockery." },
      },
      { include: ["src/**"], exclude: ["internal/mocks/"] },
    );
    expect(Object.fromEntries([...v].map(([p, i]) => [p, i.source]))).toEqual({
      "src/app.ts": "repo",
      "pnpm-lock.yaml": "lockfile",
      "gen/client.ts": "marker",
      "schema/out.graphql": "gitattributes",
      // *.pb.go un-marked by .gitattributes, mocks by the repo exclude
    });
    expect(v.get("schema/out.graphql")?.detail).toBe("schema/*.graphql linguist-generated");
  });

  it("an exact path beats a glob, in either direction", () => {
    expect(repoVerdict({ include: ["src/app.ts"], exclude: ["src/**"] }, "src/app.ts")).toBe("src/app.ts");
    expect(repoVerdict({ include: ["*.ts"], exclude: ["src/app.ts"] }, "src/app.ts")).toBe(false);
    expect(repoVerdict({ include: ["*.ts"], exclude: ["src/**"] }, "src/app.ts")).toBe(false);
    expect(withGeneratedOverride({ include: ["a/b.ts", "*.x"], exclude: [] }, "a/b.ts", false)).toEqual({
      include: ["*.x"],
      exclude: ["a/b.ts"],
    });
  });

  it("matches patterns gitignore-style", () => {
    expect(matchesPattern("*.lock", "deep/dir/x.lock")).toBe(true);
    expect(matchesPattern("/x.lock", "deep/x.lock")).toBe(false);
    expect(matchesPattern("/x.lock", "x.lock")).toBe(true);
    expect(matchesPattern("vendor/", "vendor/a/b.go")).toBe(true);
    expect(matchesPattern("docs/**/*.json", "docs/swagger/swagger.json")).toBe(true);
  });

  it("reads .gitattributes like git: last match wins, vendored marks", () => {
    const rules = parseGitattributes("# c\n*.js linguist-vendored\ndist/** linguist-generated=true\ndist/keep.js linguist-generated=false\n*.md text\n");
    expect(gitattributesVerdict(rules, "dist/a.js")?.generated).toBe(true);
    expect(gitattributesVerdict(rules, "dist/keep.js")?.generated).toBe(false);
    expect(gitattributesVerdict(rules, "lib/x.js")).toEqual({ generated: true, detail: "*.js linguist-vendored" });
    expect(gitattributesVerdict(rules, "README.md")).toBeUndefined();
  });

  it("finds a marker only in the first lines, cleaned of comment leaders", () => {
    expect(markerIn(["// Code generated by protoc-gen-go. DO NOT EDIT."])).toBe("Code generated by protoc-gen-go. DO NOT EDIT.");
    expect(markerIn(["a", "b", "c", "d", "e", "# DO NOT EDIT"])).toBeUndefined();
  });

  it("never marks a binary file or a .sql file by path", () => {
    const sql = parseDiff(file("internal/sqlc/queries/x.sql", "SELECT 1;"));
    expect(classifyGenerated(sql, { gitattributes: null, markers: {} }).size).toBe(0);
    const bin: FileDiff[] = [{ path: "go.sum", status: "modified", binary: true, hunks: [] }];
    expect(classifyGenerated(bin, { gitattributes: null, markers: {} }).size).toBe(0);
  });
});

/* ------------------------------------------------------------- lifecycle */

const key: PrKey = { host: "github.com", owner: "acme", repo: "widgets", number: 7 };
const remote = { headSha: "head1", diff: REV1, attrs: "schema/** linguist-generated\n" as string | null };
let root: string;
let graphqlCalls = 0;

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), "purview-generated-test-"));
  remote.headSha = "head1";
  remote.diff = REV1;
  graphqlCalls = 0;
  setGhRunner((args) => {
    if (args[0] !== "api") throw new Error(`unexpected gh ${args.join(" ")}`);
    if (args[1] === "graphql") {
      const q = args.find((a) => a.startsWith("query=")) ?? "";
      if (!q.includes("object(expression")) throw new Error("no graphql");
      graphqlCalls++;
      // Lockfiles, generated paths and files whose hunks show line 1 are
      // never read.
      expect(q).not.toContain("pnpm-lock.yaml");
      expect(q).not.toContain("gen/client.ts");
      const repo: Record<string, unknown> = {};
      for (const m of q.matchAll(/f(\d+):object\(expression:"[^:]+:([^"]+)"\)/g)) {
        const mock = m[2] === "internal/mocks/mocks.go";
        repo[`f${m[1]}`] = q.includes("byteSize")
          ? { byteSize: 120, isBinary: false }
          : { text: mock ? "// Code generated by mockery v2. DO NOT EDIT.\n\npackage mocks\n" : "package x\n" };
      }
      return JSON.stringify({ data: { repository: repo } });
    }
    if (args.includes("-H")) return remote.diff;
    const endpoint = args[1];
    if (endpoint.includes("/contents/.gitattributes")) {
      if (remote.attrs === null) throw new Error("gh: Not Found (HTTP 404)");
      return JSON.stringify({ type: "file", encoding: "base64", content: Buffer.from(remote.attrs).toString("base64") });
    }
    if (endpoint.includes("/compare/")) return JSON.stringify({ merge_base_commit: { sha: "mb1" } });
    if (/\/pulls\/\d+$/.test(endpoint))
      return JSON.stringify({
        node_id: "PR_x",
        number: key.number,
        title: "t",
        html_url: "https://github.com/acme/widgets/pull/7",
        state: "open",
        base: { ref: "main", sha: "base1" },
        head: { ref: "feature", sha: remote.headSha },
      });
    throw new Error(`unexpected gh api ${endpoint}`);
  });
});

afterEach(() => {
  setGhRunner(null);
  fs.rmSync(root, { recursive: true, force: true });
});

const genUnit = (s: State) => s.units.find((u) => u.id === GENERATED_UNIT_ID);
const pathsOf = (s: State) => s.generated.map((g) => g.path).sort();
const hunksOf = (p: string) =>
  readFilesJson(key, loadRev(), root).files.find((f) => f.path === p)!.hunks.map((h) => h.id);
let lastState: State;
const loadRev = () => lastState.currentRevision;

function analyzeAll(state: State) {
  const ids = state.files.filter((f) => !state.generated.some((g) => g.path === f.path)).flatMap((f) => f.hunkIds);
  return setAnalysis(
    key,
    {
      summary: "s",
      units: [
        { id: "core", title: "Core", summary: "s", kind: "core-logic", attention: "must-read", attentionWhy: "w", riskFlags: [], hunkIds: ids, order: 0 },
      ],
    },
    {},
    root,
  ).state;
}

describe("generated unit across the PR's life", () => {
  it("is built on init, before any analysis, from every signal", () => {
    lastState = initPr(key, root).state;
    expect(pathsOf(lastState)).toEqual([
      "api/v1/thing.pb.go",
      "gen/client.ts",
      "internal/mocks/mocks.go",
      "pnpm-lock.yaml",
      "schema/out.graphql",
    ]);
    expect(graphqlCalls).toBe(2); // sizes, then text — never one call per file
    const unit = genUnit(lastState)!;
    expect(unit).toMatchObject({ origin: "generated", attention: "skip", title: "Generated & lockfiles" });
    expect(unit.summary).toMatch(/^1 lockfile, 4 generated files · \+\d+ −0$/);
    expect(unit.attentionWhy).toContain(".gitattributes");
    expect(analysisUnits(lastState)).toEqual([]);
    // Nothing generated needs the analysis; the source file does.
    expect(needsClassification(lastState).map((h) => h.file)).toEqual(["src/app.ts"]);
    const files = readFilesJson(key, 1, root).files;
    expect(files.find((f) => f.path === "gen/client.ts")?.generated).toEqual({
      source: "marker",
      detail: "Code generated by openapi-gen. DO NOT EDIT.",
    });
    expect(readGeneratedFacts(key, 1, root)?.partial).toBe(false);
  });

  it("keeps generated hunks out of triage, show globs/--all and coverage", () => {
    lastState = initPr(key, root).state;
    const fj = readFilesJson(key, 1, root);
    const triage = renderTriage(fj);
    expect(triage).not.toContain("@@ ctx   ");
    expect(triage).toContain("GENERATED (5 files");
    expect(triage).toMatch(/pnpm-lock\.yaml \+2 -0/);
    expect(triage).toContain("src/app.ts   modified");
    expect(allSelectedHunks(fj).map((h) => h.file.path)).toEqual(["src/app.ts"]);
    expect(selectHunks(fj, ["**/*.go"])).toEqual({ hunks: [], unknown: [] });
    expect(selectHunks(fj, ["pnpm-lock.yaml"]).hunks).toHaveLength(1);
    // A full analysis covering only the non-generated hunks is accepted.
    lastState = analyzeAll(lastState);
    expect(genUnit(lastState)!.hunkIds).toHaveLength(5);
    expect(lastState.units.map((u) => u.id)).toEqual(["core", GENERATED_UNIT_ID]);
  });

  it("survives a full re-analysis that echoes it or claims its hunks", () => {
    lastState = initPr(key, root).state;
    const lock = hunksOf("pnpm-lock.yaml");
    const src = hunksOf("src/app.ts");
    expect(() =>
      setAnalysis(key, { summary: "s", units: [{ id: GENERATED_UNIT_ID, title: "x", summary: "", kind: "wiring", attention: "skip", attentionWhy: "", hunkIds: src, order: 0 }] }, {}, root),
    ).toThrow(/reserved/);
    lastState = setAnalysis(
      key,
      { summary: "s", units: [{ id: "deps", title: "Deps", summary: "", kind: "wiring", attention: "skim", attentionWhy: "", hunkIds: [...src, ...lock], order: 0 }] },
      {},
      root,
    ).state;
    expect(lastState.units.find((u) => u.id === "deps")!.hunkIds).toEqual(src);
    expect(genUnit(lastState)!.hunkIds).toContain(lock[0]);
  });

  it("refuses patches to it, or that take its hunks", () => {
    lastState = analyzeAll(initPr(key, root).state);
    expect(() => setUnits(key, [{ unitId: GENERATED_UNIT_ID, payload: { title: "x" } }], root)).toThrow(/cannot be patched/);
    expect(() => setUnits(key, [{ unitId: "core", payload: { addHunkIds: hunksOf("pnpm-lock.yaml") } }], root)).toThrow(
      /belong to generated files/,
    );
  });

  it("is rebuilt on a new revision; viewed state follows hunk ids; no husk", () => {
    lastState = analyzeAll(initPr(key, root).state);
    lastState = setUnitViewed(key, GENERATED_UNIT_ID, true, root);
    expect(readiness(lastState).mustRead.total).toBe(1);
    remote.diff = REV2;
    remote.headSha = "head2";
    lastState = refreshPr(key, root).state;
    expect(lastState.currentRevision).toBe(2);
    expect(pathsOf(lastState)).toEqual(["api/v1/thing.pb.go", "internal/mocks/mocks.go", "pnpm-lock.yaml", "schema/out.graphql"]);
    const unit = genUnit(lastState)!;
    expect(unit.removedAtRevision).toBeUndefined();
    expect(lastState.units.filter((u) => u.id === GENERATED_UNIT_ID)).toHaveLength(1);
    // the identical lockfile hunk stays viewed; the reworked .pb.go one is new
    expect(lastState.hunks[hunksOf("pnpm-lock.yaml")[0]].viewed).toBe(true);
    expect(lastState.hunks[hunksOf("api/v1/thing.pb.go")[0]].viewed).toBe(false);
    // generated hunks never count as work for the incremental analysis
    expect(needsClassification(lastState).map((h) => h.file)).toEqual(["src/app.ts"]);
  });

  it("disappears when no generated file is left", () => {
    lastState = initPr(key, root).state;
    remote.diff = SRC;
    remote.headSha = "head2";
    lastState = refreshPr(key, root).state;
    expect(genUnit(lastState)).toBeUndefined();
    expect(lastState.units.some((u) => u.title === "Generated & lockfiles")).toBe(false);
  });

  it("override: un-marking hands the hunks to the analysis; marking pulls them in", () => {
    lastState = analyzeAll(initPr(key, root).state);
    const lock = hunksOf("pnpm-lock.yaml");
    let res = setGeneratedOverride(key, "pnpm-lock.yaml", false, root);
    lastState = res.state;
    expect(res.changed).toBe(true);
    expect(res.generated).not.toContain("pnpm-lock.yaml");
    expect(readRepoConfig({ host: key.host, owner: key.owner, repo: key.repo }, root).generated).toEqual({
      include: [],
      exclude: ["pnpm-lock.yaml"],
    });
    expect(genUnit(lastState)!.hunkIds).not.toContain(lock[0]);
    expect(needsClassification(lastState).map((h) => h.id)).toEqual(lock);
    expect(readFilesJson(key, 1, root).files.find((f) => f.path === "pnpm-lock.yaml")?.generated).toBeUndefined();

    res = setGeneratedOverride(key, "src/app.ts", true, root);
    lastState = res.state;
    // "core" held only src/app.ts: it goes rather than staying empty
    expect(lastState.units.find((u) => u.id === "core")).toBeUndefined();
    expect(genUnit(lastState)!.hunkIds).toContain(hunksOf("src/app.ts")[0]);
    expect(readFilesJson(key, 1, root).files.find((f) => f.path === "src/app.ts")?.generated).toEqual({
      source: "repo",
      detail: "src/app.ts",
    });
    // The log alone folds to the same state.
    expect(fold(readEvents(key, root)).units).toEqual(lastState.units);
    expect(() => setGeneratedOverride(key, "nope.ts", true, root)).toThrow(/not a file/);
  });

  it("a discard re-applies settings changed on the discarded revision", () => {
    lastState = initPr(key, root).state;
    remote.diff = REV2;
    remote.headSha = "head2";
    refreshPr(key, root);
    setGeneratedOverride(key, "pnpm-lock.yaml", false, root);
    lastState = discardRevision(key, 2, root).state;
    expect(lastState.currentRevision).toBe(1);
    expect(pathsOf(lastState)).not.toContain("pnpm-lock.yaml");
    expect(genUnit(lastState)!.hunkIds).not.toContain(hunksOf("pnpm-lock.yaml")[0]);
  });

  it("backfills a revision recorded before classification existed, on a no-op refresh", () => {
    lastState = initPr(key, root).state;
    // Simulate an old log: strip `generated` from revision-added and drop the facts.
    const file = path.join(root, key.host, key.owner, key.repo, String(key.number), "events.jsonl");
    const lines = fs.readFileSync(file, "utf8").trim().split("\n").map((l) => {
      const e = JSON.parse(l);
      delete e.generated;
      return JSON.stringify(e);
    });
    fs.writeFileSync(file, lines.join("\n") + "\n");
    fs.rmSync(path.join(root, key.host, key.owner, key.repo, String(key.number), "revisions/1/generated-facts.json"));
    expect(genUnit(fold(readEvents(key, root)))).toBeUndefined();
    lastState = refreshPr(key, root).state;
    expect(genUnit(lastState)).toBeDefined();
    expect(lastState.generatedRevision).toBe(1);
    // and a second no-op refresh appends nothing
    const n = readEvents(key, root).length;
    refreshPr(key, root);
    expect(readEvents(key, root).length).toBe(n);
  });

  it("a settings change re-classifies from cached facts without the network", () => {
    lastState = initPr(key, root).state;
    const calls = graphqlCalls;
    writeRepoConfig({ host: key.host, owner: key.owner, repo: key.repo }, { generated: { include: [], exclude: ["*.pb.go"] } }, root);
    lastState = refreshPr(key, root).state;
    expect(pathsOf(lastState)).not.toContain("api/v1/thing.pb.go");
    expect(graphqlCalls).toBe(calls);
  });
});
