import { z } from "zod";
import { globToRegExp } from "./hunk-select.js";
import type {
  FileDiff,
  GeneratedFile,
  GeneratedInfo,
  GeneratedPatterns,
  GeneratedSource,
  ReviewUnit,
} from "./schemas.js";

/**
 * Generated files and lockfiles, handled deterministically.
 *
 * When a revision is recorded Purview decides, per file, whether it is
 * generated (first match wins):
 *
 *   repo          `generated.exclude` in repo.json un-marks (beats everything),
 *                 `generated.include` marks; an exact path beats a glob;
 *   gitattributes the repo's root `.gitattributes` at the PR head:
 *                 `linguist-generated` / `linguist-vendored` mark,
 *                 `-linguist-generated` / `linguist-generated=false` un-mark;
 *   lockfile      a known lockfile name;
 *   path          a generated-output path (`*.pb.go`, sqlc output, …);
 *   marker        "Code generated" / "DO NOT EDIT" / "@generated" in the
 *                 file's first lines.
 *
 * Binary files are never generated by this. Every hunk of a generated file
 * goes to one fixed unit (GENERATED_UNIT_ID) that the reducer rebuilds; the
 * analysis never reads those hunks.
 *
 * This module is pure. The network/checkout reads that produce the facts
 * (the `.gitattributes` text, the marker lines) live in generated-io.ts and
 * are cached per revision, so re-classifying after a settings change costs
 * nothing.
 */

export const GENERATED_UNIT_ID = "generated";
export const GENERATED_UNIT_TITLE = "Generated & lockfiles";

export const LOCK_FILES = new Set([
  "pnpm-lock.yaml",
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "bun.lockb",
  "bun.lock",
  "go.sum",
  "go.work.sum",
  "Cargo.lock",
  "poetry.lock",
  "uv.lock",
  "Pipfile.lock",
  "Gemfile.lock",
  "composer.lock",
  "flake.lock",
  "packages.lock.json",
  "mix.lock",
  "pubspec.lock",
  "Podfile.lock",
]);

export const GEN_PATH_RE =
  /(\.pb\.go$|_generated\.|\.gen\.|\/generated\/|\.sql\.go$|__generated__|\.d\.ts$.*\/dist\/)/;
/**
 * sqlc's non-`.sql.go` outputs. A `/sqlc/` directory alone means nothing: the
 * hand-written query files (`sqlc/queries/*.sql`) live there too, and they
 * are the source, not the output.
 */
export const SQLC_GEN_PATH_RE = /(^|\/)sqlc\/(.*\/)?(models|db|querier|copyfrom|batch)\.go$/;
export const GEN_TEXT_RE = /(Code generated|DO NOT EDIT|@generated)/;

/** How many leading lines of a file are searched for a generated marker. */
export const MARKER_LINES = 5;

export function isLockFile(p: string): boolean {
  return LOCK_FILES.has(p.split("/").pop() ?? p);
}

/** Generated by path alone. A `.sql` file never is (sqlc queries, migrations). */
export function isGeneratedPath(p: string): boolean {
  return !p.endsWith(".sql") && (GEN_PATH_RE.test(p) || SQLC_GEN_PATH_RE.test(p));
}

/* ------------------------------------------------------------- patterns */

/**
 * gitignore-ish glob match: a leading `/` anchors at the root, a pattern
 * without any other `/` matches the file name in any directory, a trailing
 * `/` or `/**` matches everything below a directory.
 */
export function matchesPattern(pattern: string, filePath: string): boolean {
  let p = pattern.trim();
  if (p === "") return false;
  if (p.endsWith("/")) p += "**";
  const anchored = p.startsWith("/");
  if (anchored) p = p.slice(1);
  if (p === filePath) return true;
  if (!anchored && !p.includes("/")) {
    return globToRegExp(p).test(filePath.split("/").pop() ?? filePath);
  }
  return globToRegExp(p).test(filePath);
}

interface AttrRule {
  pattern: string;
  /** true = mark, false = un-mark; absent = the line says nothing about it */
  generated?: boolean;
  vendored?: boolean;
}

function attrValue(attr: string, name: string): boolean | undefined {
  if (attr === name || attr === `${name}=true`) return true;
  if (attr === `-${name}` || attr === `${name}=false` || attr === `!${name}`) return false;
  return undefined;
}

/** The `linguist-generated` / `linguist-vendored` lines of a `.gitattributes`. */
export function parseGitattributes(text: string): AttrRule[] {
  const rules: AttrRule[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    const [pattern, ...attrs] = line.split(/\s+/);
    const rule: AttrRule = { pattern };
    for (const a of attrs) {
      const g = attrValue(a, "linguist-generated");
      if (g !== undefined) rule.generated = g;
      const v = attrValue(a, "linguist-vendored");
      if (v !== undefined) rule.vendored = v;
    }
    if (rule.generated !== undefined || rule.vendored !== undefined) rules.push(rule);
  }
  return rules;
}

/**
 * What `.gitattributes` says about one path: like git, the last matching
 * line wins per attribute. `generated: false` is an explicit un-mark.
 */
export function gitattributesVerdict(
  rules: AttrRule[],
  filePath: string,
): { generated: boolean; detail: string } | undefined {
  let gen: AttrRule | undefined;
  let ven: AttrRule | undefined;
  for (const r of rules) {
    if (!matchesPattern(r.pattern, filePath)) continue;
    if (r.generated !== undefined) gen = r;
    if (r.vendored !== undefined) ven = r;
  }
  if (gen?.generated === false) return { generated: false, detail: `${gen.pattern} -linguist-generated` };
  if (gen?.generated) return { generated: true, detail: `${gen.pattern} linguist-generated` };
  if (ven?.vendored) return { generated: true, detail: `${ven.pattern} linguist-vendored` };
  return undefined;
}

/* --------------------------------------------------------------- markers */

/** The marker line among a file's first lines, cleaned of comment leaders. */
export function markerIn(lines: string[]): string | undefined {
  for (const line of lines.slice(0, MARKER_LINES)) {
    if (!GEN_TEXT_RE.test(line)) continue;
    const cleaned = line
      .trim()
      .replace(/^(\/\/+|#+|--+|\/\*+|\*+|<!--|;+)\s*/, "")
      .replace(/\s*(\*\/|-->)$/, "")
      .trim();
    return cleaned.length > 120 ? cleaned.slice(0, 119) + "…" : cleaned;
  }
  return undefined;
}

/**
 * A file's first lines as its hunks show them, when they do: a hunk starting
 * at line 1 of the side that matters (the new file, or the old one for a
 * deletion). `undefined` when no hunk covers the top of the file — the head
 * content has to be read to know.
 */
export function leadingLinesFromHunks(file: FileDiff): string[] | undefined {
  const removed = file.status === "removed";
  const first = file.hunks[0];
  if (!first) return undefined;
  if ((removed ? first.oldStart : first.newStart) > 1) return undefined;
  const drop = removed ? "+" : "-";
  return first.text
    .split("\n")
    .filter((l) => l[0] !== drop && l[0] !== "\\")
    .map((l) => l.slice(1));
}

/* ------------------------------------------------------------------ facts */

/**
 * What one revision's classification needs beyond files.json, read once
 * (generated-io.ts) and cached as `revisions/<n>/generated-facts.json`.
 * Independent of the repo settings, so a settings change re-classifies from
 * it without any network.
 */
export const GeneratedFactsSchema = z.object({
  headSha: z.string().optional(),
  fetchedAt: z.string(),
  /** root `.gitattributes` at the head; null = none, or unreadable (see `partial`) */
  gitattributes: z.string().nullable().default(null),
  /** path -> marker line, for every file found to carry one */
  markers: z.record(z.string(), z.string()).default({}),
  /** some read failed (not just "absent"): the next refresh reads again */
  partial: z.boolean().default(false),
});
export type GeneratedFacts = z.infer<typeof GeneratedFactsSchema>;

/**
 * Files whose head content must be read for the marker signal: their hunks
 * don't show the top of the file, and no config-independent signal
 * (gitattributes either way, lockfile, path) already decides them.
 */
export function markerCandidates(files: FileDiff[], gitattributes: string | null): FileDiff[] {
  const rules = gitattributes ? parseGitattributes(gitattributes) : [];
  return files.filter(
    (f) =>
      !f.binary &&
      f.status !== "removed" &&
      !isLockFile(f.path) &&
      !isGeneratedPath(f.path) &&
      !gitattributesVerdict(rules, f.path) &&
      leadingLinesFromHunks(f) === undefined,
  );
}

/** Markers visible in the hunks themselves (no reads needed). */
export function markersFromHunks(files: FileDiff[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const f of files) {
    if (f.binary) continue;
    const lines = leadingLinesFromHunks(f);
    const m = lines && markerIn(lines);
    if (m) out[f.path] = m;
  }
  return out;
}

/* ---------------------------------------------------------- classification */

const isExact = (pattern: string, filePath: string) => pattern.trim().replace(/^\//, "") === filePath;

/**
 * What the repo settings say about a path: the matching include pattern,
 * `false` for an exclude, `undefined` for nothing. An exact path (what the
 * UI's "Not generated" / "Treat as generated" writes) beats any glob; between
 * globs, exclude beats include.
 */
export function repoVerdict(patterns: GeneratedPatterns, filePath: string): string | false | undefined {
  if (patterns.exclude.some((g) => isExact(g, filePath))) return false;
  const exact = patterns.include.find((g) => isExact(g, filePath));
  if (exact !== undefined) return exact;
  if (patterns.exclude.some((g) => matchesPattern(g, filePath))) return false;
  return patterns.include.find((g) => matchesPattern(g, filePath));
}

/**
 * The settings after the reader said `filePath` is (or is not) generated:
 * the exact path goes into one list and out of the other. Globs are left
 * alone — the exact path beats them (see repoVerdict).
 */
export function withGeneratedOverride(
  patterns: GeneratedPatterns,
  filePath: string,
  generated: boolean,
): GeneratedPatterns {
  const drop = (list: string[]) => list.filter((g) => !isExact(g, filePath));
  const add = (list: string[]) => [...drop(list), filePath];
  return generated
    ? { include: add(patterns.include), exclude: drop(patterns.exclude) }
    : { include: drop(patterns.include), exclude: add(patterns.exclude) };
}

/** Each file's verdict; files absent from the map are not generated. */
export function classifyGenerated(
  files: FileDiff[],
  facts: Pick<GeneratedFacts, "gitattributes" | "markers">,
  patterns: GeneratedPatterns = { include: [], exclude: [] },
): Map<string, GeneratedInfo> {
  const rules = facts.gitattributes ? parseGitattributes(facts.gitattributes) : [];
  const out = new Map<string, GeneratedInfo>();
  for (const f of files) {
    if (f.binary) continue;
    const p = f.path;
    const repo = repoVerdict(patterns, p);
    if (repo === false) continue;
    if (repo !== undefined) {
      out.set(p, { source: "repo", detail: repo });
      continue;
    }
    const attr = gitattributesVerdict(rules, p);
    if (attr) {
      if (attr.generated) out.set(p, { source: "gitattributes", detail: attr.detail });
      continue;
    }
    if (isLockFile(p)) {
      out.set(p, { source: "lockfile", detail: p.split("/").pop() });
      continue;
    }
    if (isGeneratedPath(p)) {
      out.set(p, { source: "path" });
      continue;
    }
    const marker = facts.markers[p];
    if (marker) out.set(p, { source: "marker", detail: marker });
  }
  return out;
}

/** `files` with each file's `generated` set from `verdicts` (and cleared elsewhere). */
export function annotateGenerated(files: FileDiff[], verdicts: Map<string, GeneratedInfo>): FileDiff[] {
  return files.map((f) => {
    const v = verdicts.get(f.path);
    const { generated: _old, ...rest } = f;
    void _old;
    return v ? { ...rest, generated: v } : rest;
  });
}

/** The event-log form of a revision's classification (files.json order). */
export function generatedFilesOf(files: FileDiff[]): GeneratedFile[] {
  return files
    .filter((f) => f.generated)
    .map((f) => ({
      path: f.path,
      source: f.generated!.source,
      ...(f.generated!.detail !== undefined ? { detail: f.generated!.detail } : {}),
      added: f.hunks.reduce((n, h) => n + h.addedLines.length, 0),
      removed: f.hunks.reduce((n, h) => n + h.removedLines.length, 0),
    }));
}

export function sameGeneratedFiles(a: GeneratedFile[], b: GeneratedFile[]): boolean {
  if (a.length !== b.length) return false;
  return a.every(
    (x, i) =>
      x.path === b[i].path &&
      x.source === b[i].source &&
      (x.detail ?? "") === (b[i].detail ?? "") &&
      x.added === b[i].added &&
      x.removed === b[i].removed,
  );
}

/* --------------------------------------------------------------- the unit */

export function isGeneratedUnit(u: Pick<ReviewUnit, "id" | "origin">): boolean {
  return u.origin === "generated" || u.id === GENERATED_UNIT_ID;
}

const SOURCE_LABEL: Record<GeneratedSource, string> = {
  repo: "repo settings",
  gitattributes: ".gitattributes",
  lockfile: "lockfile name",
  path: "generated-output path",
  marker: "generated-code marker",
};

const fmt = (n: number) => n.toLocaleString("en-US");

/**
 * The fixed unit for `generated` files holding `hunkIds`, placed after every
 * other unit. Fully determined by its inputs: rebuilt, never patched.
 */
export function buildGeneratedUnit(
  generated: GeneratedFile[],
  hunkIds: string[],
  order: number,
): ReviewUnit {
  const locks = generated.filter((g) => g.source === "lockfile").length;
  const gens = generated.length - locks;
  const added = generated.reduce((n, g) => n + g.added, 0);
  const removed = generated.reduce((n, g) => n + g.removed, 0);
  const counts = [
    locks ? `${locks} lockfile${locks === 1 ? "" : "s"}` : "",
    gens ? `${gens} generated file${gens === 1 ? "" : "s"}` : "",
  ].filter(Boolean);
  const sources = [...new Set(generated.map((g) => g.source))].map((s) => SOURCE_LABEL[s]);
  return {
    id: GENERATED_UNIT_ID,
    origin: "generated",
    title: GENERATED_UNIT_TITLE,
    summary: `${counts.join(", ")} · +${fmt(added)} −${fmt(removed)}`,
    kind: "wiring",
    attention: "skip",
    attentionWhy: `Generated or lock files: detected by Purview (${sources.join(", ")}), not read by the analysis`,
    riskFlags: [],
    hunkIds,
    order,
  };
}
