/**
 * The view model packages/web renders.
 *
 * Deliberately NOT imported from @reviewer/core: the web app talks to the
 * server over REST only and must stay compilable on its own. The server's
 * actual wire shapes live in `client.ts`, which adapts them into the types
 * below — this file is the UI's contract, `client.ts` owns the translation.
 */

export type Kind =
  | "core-logic"
  | "connective-tissue"
  | "wiring"
  | "ripple"
  | "tests"
  | "docs";

export type Attention = "must-read" | "skim" | "skip";

export type RiskFlag =
  | "auth"
  | "migration"
  | "concurrency"
  | "money"
  | "external-call"
  | "security";

export const KINDS: Kind[] = [
  "core-logic",
  "connective-tissue",
  "wiring",
  "ripple",
  "tests",
  "docs",
];

export const ATTENTIONS: Attention[] = ["must-read", "skim", "skip"];

/** A hunk as listed in revisions/<n>/files.json. */
export interface Hunk {
  id: string;
  file: string;
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  header: string;
  /**
   * Raw patch body for the hunk (the lines after the @@ header, each still
   * carrying its leading ' ', '+' or '-'). Derived by `client.ts` from the
   * `text` field core writes into files.json; only absent for hunks that
   * predate that field, in which case we recover it from the raw diff text.
   */
  lines?: string[];
  /** Content lines only, as core computed hunk identity from. */
  addedLines?: string[];
  removedLines?: string[];
}

export interface FileEntry {
  path: string;
  oldPath?: string;
  status?: "added" | "modified" | "removed" | "renamed";
  additions?: number;
  deletions?: number;
  binary?: boolean;
  /**
   * Set when Purview classified the file as generated or a lockfile (see
   * {@link FileGenerated}). Every hunk of such a file sits in the fixed
   * `generated` unit and the analysis never reads it.
   */
  generated?: FileGenerated;
  hunks: Hunk[];
}

/**
 * Which signal marked a file as generated, first match wins in this order:
 * the repo's own patterns, the PR head's `.gitattributes`
 * (`linguist-generated` / `linguist-vendored`), a known lockfile name, a
 * generated-path convention (`*.pb.go`, `__generated__/`…), or a "Code
 * generated … DO NOT EDIT" marker near the top of the file.
 */
export type GeneratedSource = "repo" | "gitattributes" | "lockfile" | "path" | "marker";

export interface FileGenerated {
  source: GeneratedSource;
  /** the matching pattern, or the marker line ("Code generated by protoc-gen-go") */
  detail?: string;
}

export interface FilesJson {
  files: FileEntry[];
}

export type FindingSeverity = "warning" | "note";

/**
 * A claim the analysis verified in the local checkout: `warning` = something
 * is likely wrong, `note` = a verified-OK answer to a question the reviewer
 * would otherwise have had to chase. `evidence` is the location(s) read.
 * Purely an annotation — nothing in the app acts on it.
 */
export interface Finding {
  severity: FindingSeverity;
  text: string;
  evidence: string;
}

/** One line about what a revision changed in a unit (see `ReviewUnit.changelog`). */
export interface UnitChangelogEntry {
  revision: number;
  text: string;
}

export interface ReviewUnit {
  id: string;
  title: string;
  summary: string;
  kind: Kind;
  attention: Attention;
  attentionWhy: string;
  riskFlags: RiskFlag[];
  hunkIds: string[];
  order: number;
  /** absent on units that verified nothing, and on any state predating findings */
  findings?: Finding[];
  /**
   * What each later revision changed in this unit, oldest first, one entry per
   * revision. Absent until an incremental analysis writes one; a full
   * re-analysis starts it fresh.
   */
  changelog?: UnitChangelogEntry[];
  /**
   * Set only on a "husk": a unit every hunk of which left the PR in this
   * revision. Husks never appear in `PrState.units` — the client adapter
   * moves them to `PrState.removedUnits` — and they vanish on the next revision.
   */
  removedAtRevision?: number;
  /** On a husk: the reader had viewed every hunk of it before they left. */
  readBeforeRemoval?: boolean;
  /**
   * Set only by Purview itself, never by the analysis: `"generated"` marks
   * the one fixed unit (id {@link GENERATED_UNIT_ID}) holding every hunk of
   * every generated file and lockfile. It is rebuilt on each revision, always
   * `skip`, and is not review work — nothing that counts progress, readiness
   * or "has this PR been analyzed" should count it.
   */
  origin?: "generated";
}

/** The id of the fixed generated-files unit (see `ReviewUnit.origin`). */
export const GENERATED_UNIT_ID = "generated";

/** The fixed unit Purview builds out of generated files and lockfiles. */
export function isGeneratedUnit(u: Pick<ReviewUnit, "origin">): boolean {
  return u.origin === "generated";
}

/** A unit whose hunks all left the PR (see `ReviewUnit.removedAtRevision`). */
export function isRemovedUnit(u: Pick<ReviewUnit, "removedAtRevision">): boolean {
  return u.removedAtRevision !== undefined;
}

/**
 * Word-level diff-of-diffs, as computed by core and served by
 * `GET /api/prs/:key/hunks/:id/diff-of-diffs`. It is line-oriented: each line
 * is unchanged/added/removed, or `modified` with a word-level breakdown.
 */
export interface WordPart {
  value: string;
  type: "same" | "added" | "removed";
}

export interface DiffOfDiffsLine {
  type: "unchanged" | "added" | "removed" | "modified";
  oldLine?: string;
  newLine?: string;
  /** word-level breakdown, only for `modified` lines */
  parts?: WordPart[];
}

export interface DiffOfDiffs {
  lines: DiffOfDiffsLine[];
  changed: boolean;
}

/**
 * The lines one revision changed, mapped onto the current revision's hunks —
 * `GET /api/prs/:key/revisions/:n/line-changes` (core's RevisionLineChanges).
 */
export interface HunkLineChange {
  currentHunkId: string;
  originHunkId: string;
  file: string;
  status: "fuzzy" | "renamed" | "new";
  /**
   * Sorted indexes into the current hunk's body lines (`hunk.lines`, the
   * `buildRows` index space) of the lines the revision introduced.
   */
  lines: number[];
  /** lines the revision deleted outright (an edit's old side is not counted) */
  removedCount: number;
  /**
   * Where those deletions sit now: `line` is the body index of the line right
   * after the deleted run (the body's length when it was at the very end).
   */
  removedAt: { line: number; count: number }[];
  /** how many of the revision's lines later revisions rewrote or removed */
  rewrittenSince: number;
  /** `rewrittenSince` by the revision that did it, sorted; absent when 0 (or from an older server) */
  rewrittenBy?: { revision: number; count: number }[];
  /** no later revision touched the hunk */
  exactAtCurrent: boolean;
  /** a later step couldn't be followed; positions assumed carried over */
  uncertain?: boolean;
  truncated?: boolean;
}

export interface GoneLineChangeHunk {
  originHunkId: string;
  lastHunkId: string;
  file: string;
  goneAtRevision: number;
  unitId?: string;
}

export interface RevisionLineChanges {
  revision: number;
  currentRevision: number;
  hunks: HunkLineChange[];
  goneCount: number;
  gone: GoneLineChangeHunk[];
}

export interface HunkState {
  viewed: boolean;
  viewedAtRevision?: number;
  changedSinceViewed: boolean;
  predecessorId?: string;
  migration?: "identical" | "fuzzy" | "renamed" | "new";
}

export interface FileRollup {
  viewed: boolean;
  viewedHunks: number;
  totalHunks: number;
  changedSinceViewed?: boolean;
  syncedToGitHub?: boolean;
}

export interface PrMeta {
  host: string;
  owner: string;
  repo: string;
  number: number;
  url: string;
  title?: string;
  author?: string;
  authorAvatarUrl?: string;
  /** The PR description as the author wrote it (markdown); absent until fetched. */
  body?: string;
  createdAt?: string;
  /** The PR's own branch (GitHub's `head.ref`). */
  headRef?: string;
  /** The branch this PR targets (absent on state not yet backfilled). */
  baseRef?: string;
  /**
   * The open PR whose head is `baseRef`, when this PR is stacked on another;
   * `null` = not stacked (or no PR heads that branch), absent = not resolved.
   */
  basePr?: BasePr | null;
  /** See `ReviewRequest`; `null` = none pending, absent = not looked up yet. */
  reviewRequest?: ReviewRequest | null;
  /** GitHub lifecycle state as of the last fetch (absent on older state). */
  prState?: PrGithubState;
  /** Local-only shelf; archived PRs never auto-analyze. */
  archived?: boolean;
}

/**
 * The user's still-pending review request on a PR. `via` is `"you"` for a
 * direct request or `"team:<slug>"` for one that came through a team.
 */
export interface ReviewRequest {
  /** ISO timestamp of the request. */
  at: string;
  /** Login of whoever requested it ("" when unknown). */
  by: string;
  via: string;
}

export interface BasePr {
  number: number;
  title: string;
  url: string;
}

/** One revision still on record (a discarded one is gone from the list). */
export interface RevisionInfo {
  revision: number;
  headSha?: string;
  /** ISO timestamp of the refresh that recorded it */
  addedAt?: string;
  baseOnly?: boolean;
}

/** POST /api/prs/:key/revisions/:n/discard. */
export interface DiscardRevisionResult {
  discarded: number;
  /** the revision now in force */
  revision: number;
}

export interface PrState {
  /** the mock's spelling of the revision in force; the server sends `currentRevision` */
  revision: number;
  /** the revision in force, as the server names it */
  currentRevision?: number;
  /** Every revision on record, oldest first. Absent on a mock that predates it. */
  revisions?: RevisionInfo[];
  summary?: string;
  /**
   * Live units only. Every consumer (progress, numbering, the rail, search,
   * space-to-next, counts) reads this, so husks are excluded at the source.
   */
  units: ReviewUnit[];
  /** Husks, shown only in the sidebar's "Removed" group. Absent = none. */
  removedUnits?: ReviewUnit[];
  hunks: Record<string, HunkState>;
  files?: Record<string, FileRollup>;
  baseOnly?: boolean;
}

/* --------------------------------------------------------- analysis jobs */

/**
 * The lifecycle of the server-side automatic analysis of one revision.
 * `queued`/`running` are live states; the other three are terminal.
 */
export type AnalysisJobStatus = "queued" | "running" | "done" | "failed" | "cancelled";

/** Where an analysis run's wall time went (see server's AnalysisMetricsSchema). */
export interface AnalysisMetrics {
  turns?: number;
  durationMs?: number;
  apiMs?: number;
  costUsd?: number;
  usage?: {
    input?: number;
    cacheCreation?: number;
    cacheRead?: number;
    output?: number;
  };
  toolCalls: Record<string, number>;
  bash: { cli: number; state: number; grep: number; sed: number; other: number };
  reads: { filesJson: number; diffPatch: number; skill: number; checkout: number; other: number };
  phases?: {
    firstInvestigationAt?: number;
    firstWriteAt?: number;
    setAnalysisAt?: number;
  };
  /** what the run was (see server's AnalysisRunInfoSchema); absent on older runs */
  run?: {
    kind?: "initial" | "refresh" | "rerun";
    /** the agent harness that ran it; the server fills in "claude-code" for older runs */
    harness?: string;
    harnessVersion?: string;
    sessionId?: string;
    cwd?: string;
    checkout?: string;
    model?: string;
    resolvedModel?: string;
    effort?: string;
    promptVersion?: string;
    /** wall-clock bracket of the run's child process */
    startedAt?: string;
    finishedAt?: string;
    wallMs?: number;
    size?: { files: number; hunks: number; added: number; removed: number };
    migration?: {
      identical: number;
      fuzzy: number;
      renamed: number;
      archived: number;
      new: number;
      changedUnits: number;
    };
  };
}

/** GET /api/prs/:key/analysis-job → `{ job }` (null when none was ever run). */
export interface AnalysisJob {
  revision: number;
  status: AnalysisJobStatus;
  startedAt?: string;
  finishedAt?: string;
  error?: string;
  /** free-form one-liner the runner reports while working */
  progress?: string;
  metrics?: AnalysisMetrics;
}

export const isJobLive = (job?: AnalysisJob | null): boolean =>
  job?.status === "queued" || job?.status === "running";

/** GitHub's own lifecycle state for the PR. */
export type PrGithubState = "open" | "draft" | "merged" | "closed";

/** GitHub's aggregated review decision; null when GitHub reports none. */
export type ReviewDecision = "approved" | "changes_requested" | "review_required";

/**
 * GET /api/prs/:key/staleness — has the PR moved on GitHub since we last
 * fetched it? `error` is set when the `gh` call failed; the server still
 * answers 200 with `stale: false`, so a failing check is simply silent.
 */
export type StalenessReason = "new-commits" | "base-moved";

export interface Staleness {
  stale: boolean;
  reasons: StalenessReason[];
  upstreamHeadSha: string | null;
  localHeadSha: string | null;
  upstreamState: PrGithubState | null;
  localState: PrGithubState | null;
  /**
   * The PR's state or review decision moved and the server already recorded
   * it: reload the PR instead of asking for a refresh. Absent from older
   * servers.
   */
  metaUpdated?: boolean;
  checkedAt: string;
  error?: string;
}

/**
 * `GET /api/prs`'s per-PR effort badge: "fast" for a PR that's mostly skim,
 * "heavy" for one with a large or risky must-read surface, `null` for
 * everything in between (deliberately most PRs). Absent/undefined only on a
 * server too old to send it; `null` means the server computed it and there's
 * nothing to badge (including "not analyzed yet").
 */
export type EffortBadge = "fast" | "heavy" | null;

export interface ReviewEffort {
  mustReadLines: number;
  /** kind-discounted lines — what the badge is derived from */
  weightedMustReadLines: number;
  mustReadUnits: number;
  riskCount: number;
  badge: EffortBadge;
}

/** GET /api/prs — flattened by `client.ts` from the server's progress envelope. */
export interface PrListEntry {
  key: string;
  meta: PrMeta;
  title?: string;
  currentRevision?: number;
  summary?: string;
  unitCount?: number;
  viewedHunks?: number;
  totalHunks?: number;
  analysisJob?: AnalysisJob | null;
  effort?: ReviewEffort | null;
  /** GitHub lifecycle state, as of the last fetch. */
  state: PrGithubState;
  reviewDecision: ReviewDecision | null;
  /** Pending review request for the user; `null` = none, absent = not looked up yet. */
  reviewRequest?: ReviewRequest | null;
  /** You opened it (its author is the `gh` user). Absent from an older server. */
  authoredByYou?: boolean;
  /** ISO timestamp of when this PR was added locally. */
  addedAt: string;
  /** Local-only: hides the PR behind the repo group's archived disclosure. */
  archived: boolean;
  /**
   * The PR's whole repo is archived (its own `archived` is kept apart, so
   * unarchiving the repo restores it exactly). Absent from an older server.
   */
  repoArchived?: boolean;
}

/* --------------------------------------------------------- repos & config */

/** One repo's most recent review-watch poll, from `GET /api/repos`. */
export interface RepoWatchStatus {
  checkedAt: string;
  imported: number;
  error?: string;
}

/** GET /api/repos → `{ repos }`. */
export interface RepoSummary {
  host: string;
  owner: string;
  repo: string;
  prCount: number;
  archivedCount: number;
  hasLocalConfig: boolean;
  hasCommittedConfig: boolean;
  /** the local checkout the server resolved for this repo, if any */
  repoPath: string | null;
  /** whether this machine polls the repo for review requests (see repo settings) */
  watchReviews: boolean;
  /** this repo's most recent poll, or null if the watcher has not reached it yet */
  watch: RepoWatchStatus | null;
  /** the whole repo is archived (absent from an older server) */
  archived?: boolean;
}

/** GET /api/repos/:rkey/removal — what removing the repo would lose. */
export interface RepoRemovalSummary {
  /** `host/owner/repo` */
  repo: string;
  prCount: number;
  /** local-only drafts: lost with the repo */
  draftComments: number;
  /** in a pending review on GitHub; they stay there */
  pushedComments: number;
  /** PRs that block removal right now */
  busy: { key: string; reason: "analysis" | "chat" }[];
}

/**
 * GET/PUT /api/repos/:rkey/config.
 *
 * `local` is what this machine stores; `committed` mirrors the target repo's
 * `.purview/` folder and is read-only here (the team maintains it via git);
 * `effective` is the server's own layering of the two plus the built-in
 * defaults, so the UI never has to recompute precedence.
 */
export interface RepoConfig {
  local: {
    /** null means "inherit the global default" */
    autoAnalyze: boolean | null;
    repoPath: string | null;
    /** null = inherit */
    analysisAgent: AgentSelection | null;
    chatAgent: ChatAgentSelection | null;
    /**
     * Poll GitHub for review requests every few minutes and import them. Not
     * layered like the other fields (it is a machine behavior, not team
     * policy) — `null`/`false` are both "off"; there is no "inherit".
     */
    watchReviews: boolean | null;
    rubric: string;
    chatInstructions: string;
    /** absent from a server predating it; read as two empty lists */
    generated?: GeneratedPatterns;
  };
  committed: {
    present: boolean;
    config: Record<string, unknown> | null;
    rubric: string | null;
    chat: string | null;
  };
  effective: {
    autoAnalyze: boolean;
    repoPath: string | null;
    analysisAgent: ResolvedAgent;
    chatAgent: ResolvedAgent;
  };
  /** which layer each effective value came from (the agents carry their own) */
  sources?: {
    autoAnalyze: ConfigSource;
    repoPath: ConfigSource;
  };
}

export interface RepoConfigPatch {
  autoAnalyze?: boolean | null;
  repoPath?: string | null;
  /** written whole; null re-inherits */
  analysisAgent?: AgentSelection | null;
  chatAgent?: ChatAgentSelection | null;
  watchReviews?: boolean | null;
  rubric?: string;
  chatInstructions?: string;
  /** written whole */
  generated?: GeneratedPatterns;
}

/**
 * Per-repo overrides of the generated-file detection, one glob per entry.
 * `exclude` beats every other signal (`include` and `.gitattributes`
 * included). The file header's "Not generated" / "Treat as generated" write
 * the exact path into one of these and drop it from the other.
 */
export interface GeneratedPatterns {
  include: string[];
  exclude: string[];
}

/** POST /api/prs/:key/generated — the current revision's generated paths after the change. */
export interface SetGeneratedResult {
  ok: true;
  generated: string[];
}

/** GET/PUT /api/config — the machine-wide layer. */
export interface GlobalConfig {
  /** null = inherit, which at this layer means the harness's own defaults */
  analysisAgent: AgentSelection | null;
  chatAgent: ChatAgentSelection | null;
  /** Purview's own exact checkout of each PR's head for agent runs */
  managedCheckouts: boolean;
  /**
   * Extra GitHub logins to treat as AI reviewers in review threads, on top of
   * GitHub's own bots. Absent on a server that predates review threads.
   */
  aiReviewers?: string[];
  /** what this layer resolves to on its own — the end of the chain */
  effective: { analysisAgent: ResolvedAgent; chatAgent: ResolvedAgent };
}

export interface GlobalConfigPatch {
  analysisAgent?: AgentSelection | null;
  chatAgent?: ChatAgentSelection | null;
  managedCheckouts?: boolean;
  aiReviewers?: string[];
}

/**
 * GET /api/lan — served only to the machine Purview runs on, because `url`
 * has the access token in it.
 */
export interface LanAccess {
  /** Whether this run was started with `--lan` and is actually reachable. */
  active: boolean;
  /** The address to open on the other device, token and all; null when inactive. */
  url: string | null;
  qrSvg: string | null;
  /** The server's own wording of what handing that URL over gives away. */
  warning: string;
}

/** GET /api/prs/:key */
export interface PrDetail {
  key: string;
  meta: PrMeta;
  state: PrState;
  files: FilesJson;
  diff: string;
  analysisJob?: AnalysisJob | null;
  /** `meta.basePr` is tracked in Purview too (so it can be linked in-app). */
  basePrTracked?: boolean;
  /** Pending review request for the user; `null` = none, absent = not looked up yet. */
  reviewRequest?: ReviewRequest | null;
  /**
   * A refresh left work for an analysis but none started, and why (only
   * `"archived"` is recorded). `null`/absent = nothing pending.
   */
  analysisPending?: AnalysisPending | null;
  /** the PR's whole repo is archived, so the PR behaves as archived too */
  repoArchived?: boolean;
  /** what changed since the reader's last submitted review; null/absent: nothing to compare */
  sinceReview?: SinceReview | null;
}

/** The PR-level "since your last review" filter's data (server: since-review.ts). */
export interface SinceReview {
  /** the revision the review was submitted on */
  revision: number;
  ts: string;
  event: string;
  url?: string;
  /** current hunks that were not in that revision: changed or new since */
  changedHunkIds: string[];
}

export interface AnalysisPending {
  revision: number;
  reason: "archived";
}

export interface MigrationReportItem {
  hunkId: string;
  file?: string;
  predecessorId?: string;
  note?: string;
}

/**
 * POST /api/prs/:key/refresh.
 * Core reports one flat `entries` array tagged with a status (and calls
 * carried-over-unchanged hunks `identical`); `client.ts` buckets it into the
 * per-status lists this panel renders.
 */
export interface MigrationReport {
  revision?: number;
  baseOnly?: boolean;
  counts?: {
    carried?: number;
    fuzzy?: number;
    renamed?: number;
    archived?: number;
    new?: number;
  };
  carried?: MigrationReportItem[];
  fuzzy?: MigrationReportItem[];
  renamed?: MigrationReportItem[];
  archived?: MigrationReportItem[];
  new?: MigrationReportItem[];
  /** true when refresh found no new revision (head/base/mergeBase unchanged) */
  noChange?: boolean;
}

/**
 * Three states, mirroring the server:
 *   draft     — local only.
 *   pushed    — in your PENDING review on GitHub; private, still revocable.
 *   submitted — went out with a submitted review; public.
 */
export type CommentStatus = "draft" | "pushed" | "submitted";

/**
 * What a comment is attached to. `"line"` is the historical shape (and the
 * default when the server omits the field); `"file"` comments hang off the
 * whole file and carry no line or side at all.
 */
export type CommentSubject = "line" | "file";

export interface DraftComment {
  id: string;
  file: string;
  /** null for file-level comments */
  line: number | null;
  /** null for file-level comments */
  side: "LEFT" | "RIGHT" | null;
  body: string;
  createdAt?: string;
  status?: CommentStatus;
  /** absent on older servers — treat as "line" */
  subjectType?: CommentSubject;
  /** set once the comment exists on GitHub; needed to mirror an edit remotely */
  githubCommentId?: number;
  /** who created it; absent means the reader */
  author?: CommentActor;
  /** who made the latest body edit still in effect; absent = unedited (or undone) */
  lastEditedBy?: CommentActor;
  /** earlier bodies, oldest first — what "undo" goes back to */
  history?: { body: string; replacedAt: string; replacedBy: CommentActor }[];
  /** GraphQL node id of the GitHub thread this comment started, once pushed */
  githubThreadId?: string;
  /**
   * A reply to an existing GitHub review thread (GraphQL node id). Anchored
   * to the thread's file/line for display; pushed into the pending review
   * with `addPullRequestReviewThreadReply` instead of starting a new thread.
   */
  inReplyTo?: string;
}

/** The reader, or the review chat writing through `reviewer-state comment`. */
/**
 * The reader, or an agent in the review chat (and the harness it ran on).
 * The server reads comments stored as "claude" as `{ agent: "claude-code" }`.
 */
export type CommentActor = "you" | { agent: string };

/** A deleted draft, still restorable for a while (the server's trash). */
export type DeletedComment = DraftComment & { deletedAt: string; deletedBy: CommentActor };

/** The one predicate the whole UI branches on. Tolerant of older payloads. */
export function isFileComment(c: {
  subjectType?: CommentSubject;
  line?: number | null;
}): boolean {
  return c.subjectType === "file" || c.line === null || c.line === undefined;
}

/**
 * POST /api/prs/:key/comments — one shape for both kinds, so callers can pass
 * a target around without branching until the wire.
 */
export type AddCommentInput = (
  | { subjectType?: "line"; file: string; line: number; side: "LEFT" | "RIGHT"; body: string }
  | { subjectType: "file"; file: string; body: string }
) & {
  /** reply to this GitHub thread (node id) rather than start a new one */
  inReplyTo?: string;
};

/**
 * PATCH /api/prs/:key/comments/:id
 *
 * `remote` is null for a purely local (draft) edit. For a pushed/submitted
 * comment it reports whether GitHub was updated too — `ok: false` means the
 * local edit is saved but GitHub still shows the old text.
 */
export interface EditCommentResult {
  comment: DraftComment;
  remote: { ok: true } | { ok: false; reason: string } | null;
}

export interface SyncResult {
  filesSynced?: number;
  commentsPosted?: number;
  reviewUrl?: string;
  drift?: string[];
  message?: string;
}

/**
 * POST /api/prs/:key/comments/:id/reanchor — a one-shot, non-applying
 * proposal for where a draft comment that fell outside the current diff
 * should move to. `ok: false` means the run itself failed (no `claude` CLI,
 * a timeout, an unparseable response); `applicable: false` means the run
 * succeeded but concluded there's nowhere safe to move the comment to.
 */
export interface ReanchorProposal {
  applicable: boolean;
  file?: string;
  line?: number;
  side?: "LEFT" | "RIGHT";
  reason: string;
}

export type ReanchorResult = { ok: true; proposal: ReanchorProposal } | { ok: false; reason: string };

/* ------------------------------------------------------- review lifecycle */

export type ReviewEvent = "APPROVE" | "REQUEST_CHANGES" | "COMMENT";

export interface ReadinessSummary {
  hunks: { viewed: number; total: number };
  units: { complete: number; total: number };
  mustRead: { complete: number; total: number; unviewed: number };
  changedSinceViewed: number;
  ready: boolean;
}

export interface ReviewSubmission {
  event: ReviewEvent;
  url?: string;
  commentCount: number;
  ts: string;
  revision: number;
}

/** GET /api/prs/:key/review */
export interface ReviewStatus {
  body: string;
  counts: { draft: number; pushed: number; submitted: number };
  /** everything a submit would carry, in file order */
  included: {
    id: string;
    file: string;
    line: number | null;
    side: "LEFT" | "RIGHT" | null;
    body: string;
    status: CommentStatus;
    subjectType?: CommentSubject;
  }[];
  pending: {
    /** false when we could not reach GitHub — status is then unknown, not "none" */
    known: boolean;
    exists: boolean;
    error?: string;
  };
  readiness: ReadinessSummary;
  lastSubmission?: ReviewSubmission;
  submittedAt?: string;
  submittedEvent?: ReviewEvent;
  submittedUrl?: string;
}

export interface SubmitReviewResult {
  event: ReviewEvent;
  url?: string;
  commentCount: number;
}

export interface DiscardPendingResult {
  discarded: boolean;
  resetToDraft: number;
}

/* ------------------------------------------------------------------- chat */

/**
 * A pointer to something in the review the reader is asking about. The server
 * resolves it into whatever context the agent needs (the unit's hunks, the file's
 * diff, the quoted lines…), so the UI only ever carries the pointer.
 */
export type ChatRefKind = "unit" | "hunk" | "file" | "line-range" | "comment";

export interface ChatRef {
  kind: ChatRefKind;
  /** unit id, hunk id or comment id, depending on `kind` */
  id?: string;
  path?: string;
  /** 1-based, inclusive, for line-range refs (and the anchor line of a comment) */
  start?: number;
  end?: number;
  /** which side of the diff the line numbers belong to */
  side?: "old" | "new";
}

export interface ChatMessage {
  role: "user" | "assistant";
  text: string;
  ts: string;
  refs?: ChatRef[];
}

/**
 * GET /api/agents: one agent harness as its manifest describes it. Settings
 * build their choices from these, and copy names the agent by `agentName`.
 */
export interface HarnessManifest {
  id: string;
  /** the product, e.g. "Claude Code" */
  name: string;
  /** what the agent is called in copy, e.g. "Claude" */
  agentName: string;
  models: { id: string; label: string }[];
  /** "none" is a real, pinnable value: set no effort at all */
  efforts: string[];
  defaults: { model: string; effort: string };
  capabilities: { resume: boolean; handoff: boolean };
}

export interface AgentsInfo {
  /** the harness a configuration that names none runs on */
  default: string;
  harnesses: HarnessManifest[];
}

/**
 * Which agent runs one kind of work, as a layer stores it. Model and effort
 * only mean something to the harness named next to them.
 */
export interface AgentSelection {
  harness: string;
  model?: string;
  effort?: string;
}

/** A chat has no effort setting. */
export type ChatAgentSelection = Omit<AgentSelection, "effort">;

/** An agent as the server resolved it through the layers. */
export interface ResolvedAgent {
  harness: string;
  model: string;
  /** analysis only */
  effort?: string;
  sources: { harness: ConfigSource; model: ConfigSource; effort?: ConfigSource };
  /** why this configuration cannot run (an unknown harness, a model it lacks) */
  problem?: string;
}

/** Which configuration layer an effective value came from. */
export type ConfigSource = "chat" | "pr" | "repo" | "committed" | "global" | "default";

/** GET /api/prs/:key/chat */
export interface ChatState {
  messages: ChatMessage[];
  sessionId: string | null;
  /** the harness the session belongs to, while there is one */
  sessionHarness: string | null;
  busy: boolean;
  /** what the next message will be sent with */
  agent: ResolvedAgent;
  /** the repo/global configuration, i.e. what "inherit" resolves to */
  configuredAgent: ResolvedAgent;
  /** non-null only when this conversation pins an agent of its own */
  sessionAgent: ChatAgentSelection | null;
}

/** POST /api/prs/:key/chat/agent */
export interface ChatAgentResult {
  agent: ResolvedAgent;
  configuredAgent: ResolvedAgent;
  sessionAgent: ChatAgentSelection | null;
  /** true when the new harness cannot continue the old harness's session */
  restartedSession: boolean;
}

/**
 * What an agent action does, whatever the harness calls the tool. Absent on
 * Purview's own steps (e.g. preparing the checkout).
 */
export const TOOL_KINDS = ["command", "read", "write", "search", "tool"] as const;
export type ToolKind = (typeof TOOL_KINDS)[number];

/** POST /api/prs/:key/chat, decoded from the SSE frames. */
export type ChatStreamEvent =
  | { type: "delta"; text: string }
  | { type: "tool"; name: string; detail?: string; kind?: ToolKind }
  | { type: "done"; message: ChatMessage }
  | { type: "error"; error: string };

/**
 * POST /api/prs/:key/chat/rewind. The session id always comes back `null`:
 * the CLI cannot truncate a session's transcript, so a rewind clears it and
 * the next turn starts fresh, replaying whatever is kept.
 */
export interface RewindChatResult {
  messages: ChatMessage[];
  sessionId: null;
  removed: number;
}

/**
 * POST /api/prs/:key/chat/handoff — loopback-only. `command` forks the chat's
 * agent session into the reader's terminal with the PR context file appended
 * to its system prompt.
 */
export interface ChatHandoff {
  command: string;
  cwd: string;
  sessionId: string;
  contextPath: string;
}

/** POST /api/prs/:key/repo-path */
export interface RepoPathResult {
  ok: boolean;
  warning?: string;
}

/* ------------------------------------------------- Purview-to-Purview share */

/**
 * The report `POST /api/prs/:key/analysis/import` answers with. Hunk ids are
 * content-derived, so importing re-anchors the export's units onto the
 * importer's own current revision by id intersection: `hunksUnassigned`
 * counts hunks of the current revision the export didn't cover,
 * `unitsDropped` counts units whose every hunk id fell out of the current
 * revision.
 */
export interface AnalysisImportReport {
  unitsImported: number;
  unitsDropped: number;
  hunksMatched: number;
  hunksUnassigned: number;
  /** false when the importer's revision differs from the exporter's */
  sameRevision: boolean;
}

/** POST /api/repos/:rkey/import-reviews */
export interface ImportReviewsResult {
  imported: string[];
  alreadyTracked: string[];
  failed: { key: string; error: string }[];
  days: number;
  /**
   * Which of `imported`'s PRs got a shared analysis imported off the PR's own
   * conversation tab instead of a fresh (paid) agent run — additive, so an
   * older server (or a test fixture predating this) simply never populates it.
   */
  sharedImports?: { key: string; author?: string; postedAt: string }[];
}

/* --------------------------------------------- PR-comment analysis sharing */

/** POST /api/prs/:key/analysis/share-to-pr */
/** Rides on POST /api/prs when adding imported a shared analysis for free. */
export interface SharedAnalysisNote {
  author?: string;
  postedAt: string;
}

export interface ShareAnalysisResult {
  commentUrl: string;
  /** true when an existing marked comment was updated rather than a new one posted */
  updated: boolean;
}

/** POST /api/prs/:key/analysis/import-from-pr */
export interface ImportFromPrResult {
  report: AnalysisImportReport;
  author?: string;
  postedAt: string;
  commentUrl: string;
}

/**
 * GET /api/prs/:key/analysis/shared — a cheap, read-only probe: is there a
 * shared analysis comment on this PR, and does it match the revision the
 * reader is currently looking at? Never throws server-side (a `gh` failure
 * degrades to `{ found: false, error }`), same idiom as `Staleness`. Called
 * on demand only — never polled.
 */
export interface SharedAnalysisProbe {
  found: boolean;
  author?: string;
  postedAt?: string;
  headSha?: string;
  sameCommit?: boolean;
  error?: string;
}

/* ------------------------------------------------------- GitHub review threads */

/**
 * Who wrote a comment on GitHub. `bot` is GitHub's own verdict (a Bot actor,
 * or a `[bot]` login) OR a login the reader listed as an AI reviewer in
 * settings; `botName` is a display name for known reviewers ("CodeRabbit").
 */
export interface RemoteAuthor {
  login: string;
  bot: boolean;
  botName?: string;
  avatarUrl?: string;
}

/** One comment inside a GitHub review thread. */
export interface RemoteComment {
  /** GraphQL node id */
  id: string;
  databaseId: number;
  author: RemoteAuthor;
  body: string;
  createdAt: string;
  /** set when edited after creation */
  updatedAt?: string;
  /** link on github.com */
  url: string;
  /** PENDING = sits in someone's (only ever the viewer's) unsubmitted review */
  reviewState: "PENDING" | "SUBMITTED";
  /** the viewer wrote it */
  isMine: boolean;
  /**
   * The id of the Purview comment this mirrors (matched on githubCommentId),
   * when there is one. The UI shows the local card instead of this copy, so a
   * comment pushed from Purview never appears twice.
   */
  localId?: string;
}

/**
 * A GitHub review thread: a root comment and its replies, anchored to a line
 * (or to a whole file). Several threads can sit on the same line.
 */
export interface RemoteThread {
  /** GraphQL node id — what reply/resolve take */
  id: string;
  path: string;
  subjectType: "line" | "file";
  /** current line on `side`; null when outdated or file-level */
  line: number | null;
  /** the line it was written on, at the commit it was written against */
  originalLine: number | null;
  /** first line of a multi-line comment, when it spans several */
  startLine: number | null;
  side: "LEFT" | "RIGHT";
  isResolved: boolean;
  /** the code it was written on changed since; `line` is then null */
  isOutdated: boolean;
  resolvedBy?: string;
  viewerCanResolve: boolean;
  viewerCanUnresolve: boolean;
  viewerCanReply: boolean;
  /** oldest first; [0] is the root */
  comments: RemoteComment[];
}

/**
 * A submitted review on the PR: its verdict and its top-level body (the
 * inline comments it carried live in `threads`). Pending reviews never appear.
 */
export interface RemoteReview {
  /** GraphQL node id */
  id: string;
  databaseId: number;
  author: RemoteAuthor;
  state: "APPROVED" | "CHANGES_REQUESTED" | "COMMENTED" | "DISMISSED";
  /** "" when the reviewer wrote nothing at the top level */
  body: string;
  submittedAt: string;
  /** link on github.com */
  url: string;
  /** inline comments submitted with this review */
  commentCount: number;
  /** the head commit it was written against (absent on older caches) */
  commitOid?: string;
  /** the viewer wrote it */
  isMine: boolean;
}

/** A comment on the PR's conversation tab (an issue comment, not on a line). */
export interface RemoteConversationComment {
  /** GraphQL node id */
  id: string;
  databaseId: number;
  author: RemoteAuthor;
  body: string;
  createdAt: string;
  /** set when edited after creation */
  updatedAt?: string;
  /** link on github.com */
  url: string;
  /** the viewer wrote it */
  isMine: boolean;
}

/**
 * GET /api/prs/:key/threads — the PR's review threads as GitHub has them,
 * plus its reviews and conversation comments (first 100 of each, oldest
 * first). Served from a per-PR cache when GitHub is unreachable: `error` is
 * then set and `fetchedAt` says how old the copy is (absent = never fetched).
 */
export interface ThreadsResponse {
  threads: RemoteThread[];
  reviews: RemoteReview[];
  conversation: RemoteConversationComment[];
  fetchedAt?: string;
  error?: string;
}

/** POST /api/prs/:key/threads/:id/resolve | /unresolve */
export interface ResolveThreadResult {
  thread: Pick<RemoteThread, "id" | "isResolved" | "resolvedBy" | "viewerCanResolve" | "viewerCanUnresolve">;
}
