import fs from "node:fs";
import path from "node:path";
import { stateRoot } from "@reviewer/core";

/**
 * Where the skill and the `reviewer-state` CLI live. Split out of analysis.ts
 * so every prompt builder can resolve them without importing the analysis
 * runner (which imports the prompt builders in turn).
 *
 * Two layouts have to resolve from the same `import.meta.url`-relative logic:
 *  - dev / from-source: this module lives at
 *    `<repo>/packages/server/{src,dist}/skill-paths.{ts,js}`, and the skill +
 *    CLI live in the monorepo at `<repo>/skills/pr-review` and
 *    `<repo>/packages/core/dist/cli.js`.
 *  - packaged (`@francofrizzo/purview`, npm): esbuild bundles this module
 *    into a single `packages/cli/dist/server.js`, shipped with no monorepo
 *    around it, so the repo-relative guess above resolves to nothing. The
 *    package's build step copies the skill to `dist/skill` and bundles the
 *    core CLI to `dist/reviewer-state.js`, both next to the bundle itself —
 *    checked first, falling back to the dev layout so nothing here needs to
 *    know which mode it's running in.
 */

function moduleDir(): string {
  return path.dirname(new URL(import.meta.url).pathname);
}

/** Repo root: `<root>/packages/server/{src,dist}/skill-paths.{ts,js}` -> `<root>`. */
function repoRoot(): string {
  return path.resolve(moduleDir(), "../../..");
}

function devSkillDir(): string {
  return path.join(repoRoot(), "skills", "pr-review");
}

function devCliPath(): string {
  return path.join(repoRoot(), "packages", "core", "dist", "cli.js");
}

function packagedSkillDir(): string {
  return path.join(moduleDir(), "skill");
}

function packagedCliPath(): string {
  return path.join(moduleDir(), "reviewer-state.js");
}

export function skillDir(): string {
  const override = process.env.PURVIEW_SKILL_DIR ?? process.env.REVIEWER_SKILL_DIR;
  if (override) return override;
  const packaged = packagedSkillDir();
  return fs.existsSync(packaged) ? packaged : devSkillDir();
}

/**
 * The built CLI script (`cli.js` / the packaged `reviewer-state.js`). Not
 * something to run directly — see `cliCommand()`.
 */
export function cliPath(): string {
  const override = process.env.PURVIEW_CLI_PATH ?? process.env.REVIEWER_CLI_PATH;
  if (override) return override;
  const packaged = packagedCliPath();
  return fs.existsSync(packaged) ? packaged : devCliPath();
}

/** Single-quote for /bin/sh. */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/** The wrapper's contents: this node running the CLI script, args passed through. */
export function cliWrapperScript(cli = cliPath(), node = process.execPath, self?: string): string {
  return [
    "#!/bin/sh",
    "# Generated by Purview: runs the reviewer-state CLI with the server's own node.",
    ...(self ? [`PURVIEW_CLI_SELF=${shq(self)}`, "export PURVIEW_CLI_SELF"] : []),
    `exec ${shq(node)} ${shq(cli)} "$@"`,
    "",
  ].join("\n");
}

/**
 * Where the wrapper lives: beside the CLI script when that directory is
 * writable (dev builds, most npx caches), else under the state root.
 */
function wrapperCandidates(cli: string): string[] {
  return [path.join(path.dirname(cli), "reviewer-state"), path.join(stateRoot(), "bin", "reviewer-state")];
}

/** Write `content` to `file` (mode 755) unless it already holds exactly that. */
function ensureExecutable(file: string, content: string): boolean {
  try {
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
    if (current !== content) {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      // Atomic replace: a run already executing the old wrapper keeps working.
      const tmp = `${file}.${process.pid}.tmp`;
      fs.writeFileSync(tmp, content, { mode: 0o755 });
      fs.renameSync(tmp, file);
    }
    fs.accessSync(file, fs.constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * The `reviewer-state` CLI as ONE executable path — what every prompt
 * names and every Bash allow rule is built from.
 *
 * It used to be `<node> <cli.js>`: two words, which a run would store in a
 * shell variable (`CLI="…"; $CLI report`) that zsh does not word-split, so
 * the call failed with exit 127. A tiny generated sh wrapper (pinning this
 * process's node, like before) makes it a single word in every install mode.
 * Falls back to the old two-word form only when no wrapper can be written.
 */
export function cliCommand(): string {
  const cli = cliPath();
  for (const file of wrapperCandidates(cli)) {
    if (ensureExecutable(file, cliWrapperScript(cli, process.execPath, file))) return file;
  }
  return `${process.execPath} ${cli}`;
}
